region               = "us-east-2"
owner                = "amazon"
ami_image_type       = "amzn2-ami-hvm-*-gp2"
vpc_cidr             = "10.0.0.0/16"
public_subnets_cidr  = "10.0.1.0/24"
private_subnets_cidr = "10.0.2.0/24"
availability_zones   = ["us-east-2a", "us-east-2b"]
port                 = [22, 80]
key_name             = "terraform-key-pair"
instance_type        = "t2.medium"